name: check-code-quality

on:
  push:
    branches: ["*"]

jobs:

  "test":
    runs-on: ubuntu-24.04
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install package
        run: python -m pip install .

      - name: Run tests
        run: python -m unittest discover -v tests
